# Generated by Django 4.0.4 on 2022-04-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_project_urlfield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='urlField',
            field=models.URLField(blank=True, null=True, verbose_name='Direccion web'),
        ),
    ]
